<a href="https://colab.research.google.com/github/muthu827052/Data-Analytics-using-Python-Project/blob/main/numpy_arr_day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

num = np.array([
    [[3,4],[5,6]],
    [[5,7],[8,7]],
    [[4,2],[3,2]]
    ])
print(num)

[[[3 4]
  [5 6]]

 [[5 7]
  [8 7]]

 [[4 2]
  [3 2]]]


In [ ]:
import numpy as np
arr = np.zeros((4,8))
print(arr)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
